### ISSUE TITLE
Display the error

### ISSUE THREAD

**Issue by Makio64** [davidpaulrosser/atom-glsl-preview#1]
Hi David!

Will be awesome if when there is an error, the plugins show it ( not only red tab ), especially for complex shader!

Thanks & good job! :+1:

**Comment by davidpaulrosser** [comment]
Hey,

Yeah it's not a bad idea. Currently the error will show through the WebKit inspector console. I'll look into implementing this soon.

**Comment by davidpaulrosser** [comment]
Hey @Makio64 !

I've just pushed a new update, you can now enable an error modal by checking 'Show Error Message' in the settings.

Hope it works well for you.

**Comment by Makio64** [comment]
Thanks, but as a newbie.. I have no idea how to do : 
For easier error debugging enable the showErrorMessage flag in the options. 

What about a radio button into the settings directly?

**Comment by davidpaulrosser** [comment]
Sorry for the confusion! That's exactly what you can do. In the package settings just check to box for the error message : )

**Comment by Makio64** [comment]
My bad, I didnt saw the options cause it need a atom restart.. =/

Thanks, you rulz!! :D

**Comment by Makio64** [comment]
There is a bug, when you have an error and display the message, if you close the glsl-preview you still see the error message and there is no way to remove it ( restart atom needed ).

**Comment by davidpaulrosser** [comment]
Good find! I've just fixed it now.

**Comment by davidpaulrosser** [comment]
Hi! 

Something  reaaly nice  happened to me recently,  it turned out to be  a great surprise. Just take a  look http://queshokanka.dougshrader.com/e4reycma

Faithfully, David Ronai
