### ISSUE TITLE
Resize issue

### ISSUE THREAD

**Issue by sakrist** [davidpaulrosser/atom-glsl-preview#10]
Shaders may receiving wrong iResolution size for render view.

Here is demonstration:
https://dl.dropboxusercontent.com/u/19073449/a58400b1ba531d4d3c693c8b892b2976.mp4

Nice plugin! I'm using it for quick experiments.
I'm not familiar with CoffeeScript, so can't fix it on my own.
Thanks

**Comment by davidpaulrosser** [comment]
I usually do this:

```
	vec2 uv = gl_FragCoord.xy/iResolution.xy;
	float aspect = iResolution.x / iResolution.y;

	vec3 color = vec3(uv.x,uv.y,0.0);

	uv.x *= aspect;
```
