### ISSUE TITLE
Problems with the mouse in preview mode?

### ISSUE THREAD

**Issue by marcthenarc** [davidpaulrosser/atom-glsl-preview#18]
Mouse cursor seems to be trapped at the lower-left position of preview.  Can anyone replicate this ?

[Screen shot of the lower-left corner of preview window](http://imgur.com/a/rzXEn)

```
vec4 WHITE = vec4(1.0,1.0,1.0,1.0);
vec4 RED = vec4(1.0,0.0,0.0,1.0);

void main()
{
    gl_FragColor = (length(gl_FragCoord.xy - iMouse.xy) <= 20.) ? RED : WHITE;
}
```

**Comment by fordhurley** [comment]
`iMouse` is on the [0, 1] range, so you need to multiply by the resolution to compare it to `glFragCoord`:

```glsl
vec4 WHITE = vec4(1.0,1.0,1.0,1.0);
vec4 RED = vec4(1.0,0.0,0.0,1.0);

void main()
{
    gl_FragColor = (length(gl_FragCoord.xy - iMouse.xy*iResolution.xy) <= 20.) ? RED : WHITE;
}
```

**Comment by marcthenarc** [comment]
Arrrrgh.  I should have seen that.  Thanks.
