### ISSUE TITLE
Enhancement - Support Textures

### ISSUE THREAD

**Issue by Makio64** [davidpaulrosser/atom-glsl-preview#2]
It will be a great addition if we can add/select texture in the preview to build more complex shaders.

Not sure how much work is it.. ?

Cheers!

**Comment by davidpaulrosser** [comment]
Yeah it's a good idea. It shouldn't be too much work if I add some sort of interface in with the preview pane. Maybe a UI that can be toggled at the bottom to add / remove textures. I'll try and implement something soon!

**Comment by davidpaulrosser** [comment]
Hey @Makio64 !

I've added texture support in the latest release: 0.8.0. Let me know if you have any issues.

**Comment by Makio64** [comment]
Sure, looks great! maybe instead of "texture" channel0 channel1 channel2 channel3 will be better to match shadertoy style.
