### ISSUE TITLE
Unpublished

### ISSUE THREAD

**Issue by fordhurley** [davidpaulrosser/atom-glsl-preview#20]
I just saw [this sad commit](https://github.com/amelierosser/atom-glsl-preview/commit/3ba61da66520ef432698f7ed00687901bc1c6da7). Is there anything I can do to help? If you're completely disinterested or busy, I'd be willing to take over maintenance. I suppose if it's already been unpublished, I could just republish a fork but I'd prefer to check with you first. Of course, having you continue with the project would be preferred over anything else. 😉

**Comment by davidpaulrosser** [comment]
I'm more than happy to transfer the repo to you if you want to continue on with it?

**Comment by fordhurley** [comment]
Oh wow, good timing! I was _just_ looking at this again. It [sounds like](http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/#transferring-ownership) that will allow me to continue publishing updates to the existing package, but I can't tell yet. Let's give it a shot!

**Comment by davidpaulrosser** [comment]
Ahh interesting, although i've already unpublished it lol

**Comment by fordhurley** [comment]
It's fine either way. I'll publish under a new name if I have to!

**Comment by mysteryDate** [comment]
I think you can republish: https://github.com/atom/apm/issues/188

**Comment by mysteryDate** [comment]
Thank you so much for your work by the way @amelierosser. This has been an invaluable tool for us.

**Comment by davidpaulrosser** [comment]
No worries, I’m glad you found it useful!

**Comment by davidpaulrosser** [comment]
@fordhurley Do you want me to transfer the repo over to you?

**Comment by fordhurley** [comment]
Yes please! It looks like I'll have to [delete my fork first](https://help.github.com/articles/about-repository-transfers/). I'll do that now.

**Comment by davidpaulrosser** [comment]
I've sent you the transfer request @fordhurley.

**Comment by fordhurley** [comment]
Looks like it went through! Thanks! I'll work through the republishing process this evening.

**Comment by fordhurley** [comment]
I had no problem republishing to the atom registry, so we're good to go!

As @mysteryDate said, thank you for all your work on this. I'll do my best to carry on the torch! 

First things first, cleaning up these issues... starting with this one!
