### ISSUE TITLE
Extension directive should occur before any non-preprocessor tokens 

### ISSUE THREAD

**Issue by piot** [davidpaulrosser/atom-glsl-preview#31]
version: 1.2.1

```
WARNING: 0:108: ' ' : extension directive should occur before any non-preprocessor tokens 
```

It seems like it doesn't like:

```
#extension GL_OES_standard_derivatives : enable
```

**Comment by fordhurley** [comment]
Yes, the reason for this is that the package adds some code to the shader _before_ your code. Namely, the built in uniforms. There are a few ways that we could support enabling extensions, but it would require some thinking.

I'm not totally clear on the value of the derivatives extension in this case, though. As I understand it, the derivative functions only work on `varying` values from the vertex shader, and our vertex shader produces none. Do you want to be able to write the vertex shader code?

**Comment by fordhurley** [comment]
This is now possible by writing a "bare" shader. See `examples/bare.glsl`.
