### ISSUE TITLE
Optional default uniforms

### ISSUE THREAD

**Issue by andystanton** [davidpaulrosser/atom-glsl-preview#35]
I would like to be able to make the inclusion of the default uniforms in the fragment shader optional. Currently if I declare the default uniforms manually I get an error stating they've already been declared:

![screen shot 2017-12-18 at 17 47 16](https://user-images.githubusercontent.com/1374614/34120736-8e247b7c-e41e-11e7-88b2-8aa8c7f0a59c.png)

The shader file then can't be validated by other means, for example using glslangValidator via the linter-glsl package as the uniform declarations aren't part of the file.

Instead I would like to be able to declare them without error like this:

![screen shot 2017-12-18 at 17 48 59](https://user-images.githubusercontent.com/1374614/34120740-91cdc968-e41e-11e7-8e54-0e45e563612c.png)

### Proposed Change

1. Modify `setShader` in shader-canvas to accept a boolean parameter to indicate whether or not to include the declarations for the default uniforms in the fragment shader. The parameter will have a default value of true for backwards compatibility. Here is what the change might look like:

https://github.com/fordhurley/shader-canvas/compare/master...andystanton:make-default-uniforms-optional?expand=1

2. Once the change to shader-canvas has been released, update glsl-preview to use the new version. This change will include a new configuration option to include the declarations for the default uniforms. The configuration will be enabled by default, again for backwards compatibility. When the configuration is disabled, a value of false will be passed to `setShader` which will mean the user is intending to declare the uniforms themselves. Here is what the change might look like:

https://github.com/fordhurley/atom-glsl-preview/compare/master...andystanton:make-default-uniforms-optional?expand=1

**Comment by fordhurley** [comment]
Yes! Thank you for starting this discussion, this has been bothering me for some time. See #31 for yet another reason that injecting those uniform definitions on their behalf is troublesome.

Your proposal sounds like the right way to handle this. I’ll take a look at the code in the next few days. Thanks!

**Comment by andystanton** [comment]
👍 I've fleshed out those changes into two PRS, and included a couple of fixes as well:

* shader-canvas: fordhurley/shader-canvas#4
* atom-glsl-preview: fordhurley/atom-glsl-preview#36

**Comment by andystanton** [comment]
Thanks for the quick turnaround @fordhurley
