### ISSUE TITLE
Shader Error 

### ISSUE THREAD

**Issue by zaverichintan** [davidpaulrosser/atom-glsl-preview#37]
![screenshot from 2017-12-27 21-32-14](https://user-images.githubusercontent.com/11918544/34386179-7136b2a6-eb4d-11e7-9e97-b33d949b045d.png)
Error in Atom:

> ERROR: 1:1: 'version' : #version directive must occur before anything else, except for comments and white space 
> ERROR: 10:1: 'in' : storage qualifier supported in GLSL ES 3.00 and above only  
> ERROR: 11:1: 'in' : storage qualifier supported in GLSL ES 3.00 and above only  
> ERROR: 17:1: 'out' : storage qualifier supported in GLSL ES 3.00 and above only  
> ERROR: 46:1: '0.0f' : Floating-point suffix unsupported prior to GLSL ES 3.00 
> ERROR: 46:1: '0.0f' : syntax error 

My code is attached as a screenshot.

Does this error occur due to incompatible GLSL version?

**Comment by fordhurley** [comment]
Yes, this shader is incompatible with WebGL 1.0, and more specifically with glsl-preview. For one, `#version directive must occur before anything else, except for comments and white space`, but glsl-preview adds some code before your shader when running it. The bigger problem is that your shader will be expecting vertex attributes and uniforms that won't be provided by glsl-preview.

It looks like you're going to be adding to this shader anyway, judging by the `YOUR CODE HERE` comment. In that case, I recommend developing _that_ code in a new file based on one of the [examples](https://github.com/fordhurley/atom-glsl-preview/tree/master/examples), then copying it over to this file.
