### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by stillsinn** [davidpaulrosser/atom-glsl-preview#39]
Argument to `path.dirname` must be a string
```
Object.dirname (/Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:9:10)
GlslPreviewView.updateShader (/Users/******/.atom/packages/glsl-preview/lib/glsl-preview-view.js:222:23)
```

**Comment by fordhurley** [comment]
Thanks for reporting. Could you tell more about what you were doing when you got this error? Maybe include the shader, or enough of it to reproduce the error?

**Comment by stillsinn** [comment]
Sorry, I don't remember the specific shader. Gonna close it, as it does not show when previewing shader currently. Might very well have been my shader causing the problem. False alarm. :)

**Comment by fordhurley** [comment]
Thanks! If it pops up again please re-open this issue. It could very well be something we should handle more gracefully at least.
