### ISSUE TITLE
Why my code not working?

### ISSUE THREAD

**Issue by ghost** [davidpaulrosser/atom-glsl-preview#47]
ERRORS:

ERROR: 7:1: 'texture' : no matching overloaded function found
ERROR: 7:1: 'rgb' :  field selection requires structure or vector on left hand side
ERROR: 7:1: '=' : dimension mismatch
ERROR: 7:1: '=' : cannot convert from 'const mediump float' to 'highp 3-component vector of float'

CODE:

uniform vec2 u_resolution;

uniform sampler2D normalmap; // normalmap.jpg

void main(void) {
  vec2 position = vec2(10.0,10.0); // TODO: Modify position
  vec3 normal = texture(normalmap,position).rgb; // LINE: 7
  normal = normalize(normal);

  gl_FragColor = vec4(normal,1.0);
}

**Comment by fordhurley** [comment]
In WebGL (OpenGL ES 2.0), the function you need is `texture2D`. That should fix it!
