### ISSUE TITLE
Not working: max, min, clamp, #version

### ISSUE THREAD

**Issue by ghost** [davidpaulrosser/atom-glsl-preview#48]
Not working: max, min, clamp AND #VERSION

**Comment by fordhurley** [comment]
I suspect that you're writing code for the wrong version of GLSL. This plugin uses WebGL, aka OpenGL ES 2.0. If you haven't seen them, there are some [examples](https://github.com/fordhurley/atom-glsl-preview/tree/master/examples) that might be helpful.

**Comment by ghost** [comment]
thanks :)

**Comment by fordhurley** [comment]
Glad that helped! 👍
