### ISSUE TITLE
GLSL Preview shows nothing but black

### ISSUE THREAD

**Issue by AnastasiaDunbar** [davidpaulrosser/atom-glsl-preview#5]
Using

```
uniform vec2 iResolution;
uniform vec2 iMouse;
uniform float iGlobalTime;
void main() {
    vec2 uv = gl_FragCoord.xy/iResolution;
    gl_FragColor = vec4(uv,0.,1.):
}
```

**Comment by sakrist** [comment]
@AnastasiaDunbar of course, because you have **:** on last line instead of **;**
;)

**Comment by AnastasiaDunbar** [comment]
@sakrist I'm still somehow not sure it would work if I tried it now because I don't have Atom and I don't remember much about of what I did.
