### ISSUE TITLE
Package not working? no preview no code compilation...

### ISSUE THREAD

**Issue by kalwalt** [davidpaulrosser/atom-glsl-preview#55]
i installed the `atom-glsl-preview` package and the `language-glsl` package, i opened one of your examples `frag.glsl`, ctrl-shift-G but nothing happens, no message no error no preview .... I tried also to use a previous version ( `**2.0.0**` )  but without luck... :sob: 

my spec: 
Atom 1.37.0
Ubuntu 18.04.02 LTS

**Comment by fordhurley** [comment]
Interesting. Does the `GLSL Preview: Toggle` command show up in the "command palette" (ctrl-shift-P)?

**Comment by kalwalt** [comment]
Yes `GLSL Preview: Toggle` is showed up but when clicking the preview not appear.

**Comment by fordhurley** [comment]
Ok, I suspect that it's detecting the wrong source language for the shader. By default, the package only loads when the file matches one of the grammars listed in the package settings here: 

<img width="746" alt="Screen Shot 2019-05-28 at 10 00 13 AM" src="https://user-images.githubusercontent.com/200646/58484101-72253d80-812f-11e9-9b6a-d4ae525f7b4f.png">

The link there is supposed to lead to this text, but that appears to be broken:

> To enable Spell Check for your current file type: put your cursor in the file, open the Command Palette (cmd-shift-p), and run the Editor: Log Cursor Scope command. This will trigger a notification which will contain a list of scopes. The first scope that's listed is the one you should add to the list of scopes in the settings for the Spell Check package. Here are some examples: `source.coffee`, `text.plain`, `text.html.basic`.

You can either add the scope you see there to the list of grammars for this package, or change the `.glsl` file to `source.glsl`. This should also make the `language-glsl` package syntax highlight your shader code properly.

If that's not the issue, let me know and we'll keep digging. If that fixes your problem, I'd like to keep this issue open as a reminder to

1. Consider making glsl-preview load no matter the current editor scope.
2. Or, show a notification when you attempt to load it in an unsupported editor scope.

Also need to fix that link in the settings and document this better in the README.

**Comment by kalwalt** [comment]
@fordhurley my shader has a correct highlight and i have the `GLSL` tag on the bottom bar, so i think the problem is not with the language-glsl package. Renaming the file to `source.glsl` has no effect.
If i have time i could try with a fresh Atom install, trying to reproduce the error again. Could be some package conflict?

**Comment by fordhurley** [comment]
Ok, I'm stumped then. If you have any updates, please let me know!

In the meantime, you might be interested in trying out https://github.com/fordhurley/shaded.

**Comment by kalwalt** [comment]
@fordhurley nice one, i use [glslViewer](https://github.com/patriciogonzalezvivo/glslViewer) but thank you to share this! If i have news i will report to you...

**Comment by kalwalt** [comment]
Hi @fordhurley recently i re installed glsl-preview in the same machine but after a reinstalling of the OS it works like a charme now. Nice to see the glsl preview in the Atom editor! Unfortunately i don't know why didn't work in the past,...  
Tested with Atom 1.44.0 and Ubuntu 18.04.03 LTS
