### ISSUE TITLE
Typed "frag", pressed enter, nothing happens.

### ISSUE THREAD

**Issue by trusktr** [davidpaulrosser/atom-glsl-preview#6]
Is it supposed to insert a snippet? Do I need other package installed first?

**Comment by fordhurley** [comment]
The snippet works for me as long as I'm in a glsl file. Maybe you're trying to run it in a brand new file? Save it first with the .glsl extension or set the syntax to GLSL, then try to insert the snippet. You might also need to look at your settings for `snippets`, `autocomplete-plus`, and `autocomplete-snippets`.
