### ISSUE TITLE
Feature request: glslify

### ISSUE THREAD

**Issue by tjlav5** [davidpaulrosser/atom-glsl-preview#7]
Hi David,

I love the plugin. I am doing a lot of work with [glslify](https://github.com/stackgl/glslify) these days and am wondering if you have any objections to a PR on adding the functionality?

**Comment by davidpaulrosser** [comment]
Hey,

Glad to hear you like it. Not at all, feel free to add functionality. What kind of features were you thinking of adding?

**Comment by tjlav5** [comment]
I'd like to add a toggle to the settings screen to toggle glslify. Are you familiar with it?

**Comment by davidpaulrosser** [comment]
Yeah i've used it on projects before. Feel free to add support for it :)
