### ISSUE TITLE
Textures not actually working on Windows platform

### ISSUE THREAD

**Issue by Abyss116** [davidpaulrosser/atom-glsl-preview#9]
Do work on my Mac though, always shows black on windows but I can add textures and can preview in the texture overlay button.

**Comment by mariotacke** [comment]
Love the plugin. Having the same issue on windows.

**Comment by gbmap** [comment]
@Abyss116 Would you mind telling me the name of the file you are attempting to load? (I hope I'm not too late to the party)

I've managed to locate and appropriately 'fix' the issue, but apparently there is a related problem with the way uniforms are being setup. Is the file by any chance called texture?

**Comment by gbmap** [comment]
#11 fixes this. It would be nice if you guys could test this.

**Comment by davidpaulrosser** [comment]
Tested it and it worked fine on OSX. Now published v0.10.0. Thank you!
